### ISSUE TITLE
Aragon Nest Proposal: Education Platform

### ISSUE THREAD

**Issue by DaniellMesquita** [aragon/nest#123]
# Aragon Nest Proposal: Education Platform

## Abstract

Before being great contributors on a project (with ideas, code, design or everything), on the begin they were newbies. I believe DAOs aren't just for team working, but also for studies; study is the basic thing before growing on their works and lead to knowledge.

Coding, human language (native and english as the most important), UX/UI design, security, and other things are needed before being a skilled contributor; but if we want to democratize the work, we need to offer an educational platform alongside it.

**Note: I don't have skills to make it working, but to propose it; then you're free to begin implementing it on a pull request and receive your grants.**

## Deliverables

1. An aragonOS-compatible application (the educational platform) that lets people create courses, learn on those courses, gets tasks/achievements, be awarded with [open badges](https://github.com/aragon/nest/issues/122) (or also monetary incentives) and share knowledge with other students

## Tasks

- [ ] Vote to create an course
- [ ] DAO will give tokens for who create and update courses
- [ ] Courses can include videos, but needs to have text also, as it is basic
- [ ] Course's text can be available in lots of languages, and their videos can support SRT subtitles
- [ ] DAO can update the course, but updates needs to be versioned (courses can use [pando](https://github.com/aragon/nest/pull/31)) and course's users needs to be aware of those updates to update their knowledge - uploading new languages/localization will be also considered as updates, and will be versioned)
- [ ] Courses from an DAO can be used on other DAOs (the DAO that created the course can earn tokens from its use)
- [ ] Other DAOs can propose updates to the course of the original DAO
- [ ] Courses haves basic info: basic skills needed, hours/time of learning, etc.
- [ ] Course's community, to share knowledge (don't make it able to share the answers)
- [ ] Course's homework/tasks (and [open badge](https://github.com/aragon/nest/issues/122) achievements for completing them)
- [ ] Courses can haves a start/finish time and study classes/groups
- [ ] Courses can have an live teacher, that will be rated by students and granted with tokens
- [ ] Live teachers can send their own homework/tasks, and create their own [open badges](https://github.com/aragon/nest/issues/122)
- [ ] API to give advanced features for courses (english course can have words to pick, coding courses can have a CodePen-like sandbox for playing)
- [ ] When user completes each module on the course, the user earns open [badges](https://github.com/aragon/nest/issues/122) (or also tokens) for each module
- [ ] When completing the course, user is awarded with an [open badge](https://github.com/aragon/nest/issues/122) (or also tokens)
- [ ] Users can post a feedback about the course after completing it 
- [ ] Referral: if user earns tokens for completing modules/course, its referrer earns a share of it
- [ ] Achievement Open Badge for referrer: each time an referral completes a module/course, he earns a badge about it (also depends on the [Open Badges app](https://github.com/aragon/nest/issues/122))

## Grant size

Funding: from $100k up to $150k in ETH, split into chunks paid out over achieved deliverables.

Success reward: Up to $100k in ANT, given out when all deliverables are ready.

## Application requirements

- Details of the team members, alongside with their willingness in terms of implication
- Estimated average burn rate for completing the deliverables
- Legal structure to be adopted, if any

## Development timeline

To be discussed or to be proposed by the team requesting funds.

**Comment by DaniellMesquita** [comment]
@abreckler
> We have a proposal for this project and the team in place to execute it.
> 
> Should we reply here with our proposal or wait for it to get reviewed // approved first before submitting our plan?

That's up to you, as your comment is part of this issue, unless you think you would waste time by writing on an proposal that could not be accepted. But I welcome you to explain how you and you team could achieve it, and to open an pull request when this proposal gets approved.

**Comment by mariapao** [comment]
Hi @DaniellMesquita thanks a lot for your submitting your proposal.

Education certainly is important, however, we are not approving this proposal at the moment. As mentioned in one of my comments to another of your proposals, this year the Nest program will be focused on funding teams building key Aragon infrastructure or applications. We are interested in tutorials for developers building on Aragon and for Aragon users but we fund such contributions with bounties. 

If in the future you are working on something that is a fit for the program, please do not hesitate to apply again!

**Comment by mariapao** [comment]
Hi @abreckler even if this proposal was not approved I want to explain the process just in case for the future. Applicants should wait until a proposal is approved. Once it is approved, they can apply by opening a pull request referring to the relevant proposal.
